#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: ./latc_x86_64 [file_name]"
    exit 1
fi

filePath=$1
fileDir=$(dirname "${filePath}")

if [ -z "$fileDir" ]; then
    fileDir="."
fi

fileNameExt=$(basename "${filePath}")
fileName="${fileNameExt%.*}"
fileBase="${fileDir}/${fileName}"
assemblyFile="${fileBase}.s"
objectFile="build/${fileName}.o"
execFile="${fileBase}"

if [ -n "$2" ]; then
    assemblyFile="output/${fileName}.s"
    execFile="output/${fileName}"
fi

build/Compiler < $filePath # > $assemblyFile
ret=$?

if [ $ret -ne 0 ]; then
    exit $ret
fi

# gcc -m32 -o $objectFile -c $assemblyFile

# ld -o $execFile -melf_i386 $objectFile lib/runtime.o /home/students/inf/PUBLIC/MRJP/lib32/{crt*.o,libc.a}

# rm $objectFile

exit 0
